# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Create Teams [Devops, Dev and Testing] with appropriate permissions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Creating Devops Team
      run: |
        echo "Login to GitHub"
        curl -i -u ranjithchannabasappa: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 https://api.github.com/users/ranjithchannabasappa
